name=jvlib
version=2026.08.29b
author=1eclectic1
maintainer=1eclectic1
sentence=Common routines for ESP8266/ESP32 IoT sensors and controllers
paragraph=WiFi, MQTT, LWT, OneWire, BME/BMP/DHT, watchdog, daily reboot, optional LittleFS manager
category=Communication
url=https://github.com/1eclectic1/iot-ut-jvlib
architectures=esp8266,esp32
includes=jvlib.h
